import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { CarFront, Check, MessageCircle } from 'lucide-react';
import { getVehicle } from '../services/vehicleService.js';
import VehicleImageGallery from '../components/VehicleImageGallery.jsx';
import LoadingSpinner from '../components/LoadingSpinner.jsx';
import ErrorState from '../components/ErrorState.jsx';
import Button from '../components/Button.jsx';
import Modal from '../components/Modal.jsx';
import QuoteForm from '../components/QuoteForm.jsx';
import { formatCurrency } from '../utils/format.js';
export default function VehicleDetailsPage(){ const {slug}=useParams(); const [v,setV]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [open,setOpen]=useState(false); useEffect(()=>{setLoading(true);getVehicle(slug).then(setV).catch(e=>setError(e.response?.data?.message||'Vehicle not found.')).finally(()=>setLoading(false));},[slug]); if(loading)return <LoadingSpinner label="Loading vehicle..."/>; if(error||!v)return <div className="container-shell py-20"><ErrorState message={error||'Vehicle not found.'}/></div>; return <section className="section-pad"><div className="container-shell"><div className="grid gap-12 lg:grid-cols-[1.15fr_.85fr]"><VehicleImageGallery images={v.images} name={v.name}/><div><p className="eyebrow">{v.type}</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">{v.name}</h1><p className="mt-5 text-lg leading-8 text-zinc-600">{v.description}</p><div className="mt-6 rounded-2xl bg-zinc-100 p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-zinc-500">Starting / demo price</p><p className="mt-1 text-2xl font-black">{formatCurrency(v.price)}</p><p className="mt-2 text-xs text-zinc-500">Verify current official pricing and availability before production use.</p></div><div className="mt-7"><h2 className="font-black">Highlights</h2><div className="mt-3 grid gap-2">{v.highlights?.map(x=><div key={x} className="flex items-center gap-2 text-sm text-zinc-600"><Check className="h-4 w-4 text-red-500"/>{x}</div>)}</div></div><div className="mt-8 flex flex-wrap gap-3"><Button onClick={()=>setOpen(true)} variant="red"><MessageCircle className="h-4 w-4"/> Inquire About This Vehicle</Button><Button onClick={()=>setOpen(true)} variant="secondary"><CarFront className="h-4 w-4"/> Request Test Drive</Button></div></div></div><div className="mt-12"><h2 className="text-2xl font-black">Key specifications</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{v.specifications?.map(s=><div key={`${s.label}-${s.value}`} className="rounded-2xl border border-zinc-200 p-5"><p className="text-xs font-bold uppercase tracking-[.12em] text-zinc-400">{s.label}</p><p className="mt-2 font-bold">{s.value}</p></div>)}</div></div></div><Modal open={open} onClose={()=>setOpen(false)} title={`Inquire about ${v.name}`}><QuoteForm defaultVehicle={v.name} compact onSuccess={()=>setTimeout(()=>setOpen(false),1200)}/></Modal></section>; }
